### ISSUE TITLE
opa mano kkkkk

### ISSUE THREAD

**Issue by Heus-Sueh** [Claudemirovsky/extension-builder#2]
tem discord para nois conversar?

sobre scraping

**Comment by Heus-Sueh** [comment]
você não teria interesse em fazer provedores para o Aplicativo [Cloudstream](https://github.com/recloudstream/cloudstream)?

aqui está a documentação dele:
https://recloudstream.github.io/csdocs/devs/gettingstarted/

eu até tentei criar um provedor, mas eu sou burro demais para fazer scraping kkkkkkk, como vc criou as extensões lá pro aniyomi eu acho que vc consegue fazer isso.

aqui estão os repositórios que você pode colocar os seus provedores:
https://github.com/hexated/cloudstream-extensions-hexated
https://github.com/821938089/cloudstream-extensions
https://github.com/hexated/cloudstream-extensions-multilingual

**Comment by Claudemirovsky** [comment]
> você não teria interesse em fazer provedores para o Aplicativo [Cloudstream](https://github.com/recloudstream/cloudstream)?
> 
> aqui está a documentação dele: https://recloudstream.github.io/csdocs/devs/gettingstarted/
> 
> eu até tentei criar um provedor, mas eu sou burro demais para fazer scraping kkkkkkk, como vc criou as extensões lá pro aniyomi eu acho que vc consegue fazer isso.
> 
> aqui estão os repositórios que você pode colocar os seus provedores: https://github.com/hexated/cloudstream-extensions-hexated https://github.com/821938089/cloudstream-extensions https://github.com/hexated/cloudstream-extensions-multilingual

Parece interessante, vou dar uma olhada nesse negócio.
